#!/usr/bin/env python3
# dashboard/run.py
# Validates that pipeline outputs exist before launching the dashboard.
# Usage: python dashboard/run.py [--port 8050]
import os
import sys
import argparse

REQUIRED = [
    ("data/logs_flagged.csv",       "src/models.py"),
    ("docs/anomaly_report.json",    "src/alerting.py"),
    ("monitoring/drift_report.json","src/alerting.py"),
    ("docs/model_meta.json",        "src/models.py"),
]

OPTIONAL = [
    ("docs/lstm_meta.json",         "src/models.py (requires torch)"),
    ("models/lstm_autoencoder.pt",  "src/models.py (requires torch)"),
]


def check_files():
    missing = []
    for path, cmd in REQUIRED:
        if not os.path.exists(path):
            missing.append((path, cmd))

    if missing:
        print("\n  Pipeline outputs not found. Run these steps first:\n")
        print("    python src/data_pipeline.py")
        print("    python src/models.py")
        print("    python src/alerting.py\n")
        print("  Missing files:")
        for path, cmd in missing:
            print(f"    {path}  (generated by {cmd})")
        print()
        return False

    for path, note in OPTIONAL:
        if not os.path.exists(path):
            print(f"  [optional] {path} not found ({note}) — LSTM charts will be empty")

    print("  All required pipeline outputs found.")
    return True


def main():
    parser = argparse.ArgumentParser(description="Launch anomaly detection dashboard")
    parser.add_argument("--port", type=int, default=8050)
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--debug", action="store_true")
    parser.add_argument("--skip-check", action="store_true",
                        help="Launch even if pipeline outputs are missing")
    args = parser.parse_args()

    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    print("\n  Anomaly Detection Dashboard")
    print("  ───────────────────────────")

    if not args.skip_check and not check_files():
        sys.exit(1)

    print(f"\n  Starting on http://{args.host}:{args.port}\n")

    from dashboard.app import app
    app.run_server(debug=args.debug, host=args.host, port=args.port)


if __name__ == "__main__":
    main()
